import{HandLandmarker,FilesetResolver,DrawingUtils}from"https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/+esm";
const q=s=>document.querySelector(s),qa=s=>document.querySelectorAll(s);
const els={video:q('#video'),canvas:q('#stage'),fps:q('#fps'),hands:q('#hands'),gesture:q('#gestureText'),tracking:q('#trackingState'),pinch:q('#pinchVal'),cursorX:q('#cursorX'),cursorY:q('#cursorY'),latency:q('#latency'),cursor:q('#cursor'),overlay:q('#startOverlay'),notice:q('#notice'),toast:q('#toast'),startBtn:q('#startBtn'),demoBtn:q('#demoBtn')};
const ctx=els.canvas.getContext('2d');let handLandmarker=null,drawingUtils=null,running=false,lastVideoTime=-1,frameCounter=0,fpsTick=performance.now(),pinchDown=false,grabbed=null,swipeHistory=[],lastSwipeAt=0,stream=null;let grabOffset={x:0,y:0};
const connections=HandLandmarker.HAND_CONNECTIONS;
function resize(){const dpr=Math.min(devicePixelRatio||1,2);els.canvas.width=Math.round(innerWidth*dpr);els.canvas.height=Math.round(innerHeight*dpr);els.canvas.style.width=innerWidth+'px';els.canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);const fingerExtended=(lm,tip,pip)=>lm[tip].y<lm[pip].y-.025;
function classify(lm,pinchDistance,didSwipe){if(didSwipe)return'SWIPE';if(pinchDistance<.055)return'PINCH';const index=fingerExtended(lm,8,6),middle=fingerExtended(lm,12,10),ring=fingerExtended(lm,16,14),pinky=fingerExtended(lm,20,18);const up=[index,middle,ring,pinky].filter(Boolean).length;if(up>=4)return'OPEN';if(up===0)return'FIST';if(index&&!middle&&!ring&&!pinky)return'POINT';return'TRACK'}
function emitGesture(name,detail={}){els.gesture.textContent=name;qa('.gesture').forEach(el=>el.classList.toggle('active',el.dataset.gesture===name));dispatchEvent(new CustomEvent('qookey-gesture',{detail:{gesture:name,...detail}}))}
function showToast(text){els.toast.textContent=text;els.toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>els.toast.classList.remove('show'),700)}
function detectSwipe(x){const now=performance.now();swipeHistory.push({x,t:now});swipeHistory=swipeHistory.filter(p=>now-p.t<260);if(swipeHistory.length<5||now-lastSwipeAt<900)return false;const dx=swipeHistory.at(-1).x-swipeHistory[0].x;if(Math.abs(dx)>.26){lastSwipeAt=now;showToast(dx>0?'SWIPE RIGHT':'SWIPE LEFT');return true}return false}
function updateCursor(screenX,screenY,isPinching){els.cursor.style.opacity='1';els.cursor.style.left=`${screenX}px`;els.cursor.style.top=`${screenY}px`;els.cursor.classList.toggle('pinching',isPinching);els.cursorX.textContent=Math.round(screenX);els.cursorY.textContent=Math.round(screenY);if(isPinching&&!pinchDown){pinchDown=true;const target=document.elementFromPoint(screenX,screenY)?.closest?.('[data-draggable]');if(target){grabbed=target;const r=target.getBoundingClientRect();grabOffset.x=screenX-r.left;grabOffset.y=screenY-r.top;target.style.transform='none';target.style.right='auto';target.style.bottom='auto';target.style.zIndex='9'}}if(!isPinching&&pinchDown){pinchDown=false;if(grabbed)grabbed.style.zIndex='4';grabbed=null}if(grabbed&&isPinching){const w=grabbed.offsetWidth,h=grabbed.offsetHeight,x=Math.max(8,Math.min(innerWidth-w-8,screenX-grabOffset.x)),y=Math.max(60,Math.min(innerHeight-h-8,screenY-grabOffset.y));grabbed.style.left=`${x}px`;grabbed.style.top=`${y}px`}}
async function initModel(){if(handLandmarker)return;els.notice.textContent='相機已允許，正在載入 MediaPipe 手部模型…';const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');handLandmarker=await HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.5});drawingUtils=new DrawingUtils(ctx)}
function permissionHelp(err){const name=err?.name||'';if(name==='NotAllowedError'||name==='PermissionDeniedError'||String(err?.message||'').includes('not allowed'))return'相機權限被瀏覽器擋住。Safari：網址列左側「網站設定」→ 相機 → 允許；若先前按過不允許，請到 Safari「設定 → 網站 → 相機」改成允許，再重新整理。';if(name==='NotFoundError')return'找不到可用相機，請確認裝置有相機且沒有被其他 App 停用。';if(!isSecureContext)return'相機只能在 HTTPS 安全頁面使用。';return`啟動失敗：${err?.message||err}`}
async function startCamera(){els.startBtn.disabled=true;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('此瀏覽器不支援相機存取');els.notice.textContent='正在要求相機權限…';stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});await initModel();els.video.srcObject=stream;await els.video.play();running=true;els.overlay.style.display='none';els.tracking.textContent='ONLINE';requestAnimationFrame(loop)}catch(err){console.error(err);stream?.getTracks().forEach(t=>t.stop());stream=null;els.notice.textContent=permissionHelp(err);els.startBtn.disabled=false}}
function draw(results){ctx.clearRect(0,0,innerWidth,innerHeight);if(els.video.readyState>=2){ctx.save();ctx.globalAlpha=.78;ctx.drawImage(els.video,0,0,innerWidth,innerHeight);ctx.restore()}const list=results?.landmarks||[];els.hands.textContent=list.length;if(!list.length){els.cursor.style.opacity='0';els.pinch.textContent='—';emitGesture('—',{hands:0});return}list.forEach((lm,i)=>{drawingUtils.drawConnectors(lm,connections,{color:'rgba(139,240,255,.68)',lineWidth:2});drawingUtils.drawLandmarks(lm,{color:'#f1feff',fillColor:'rgba(139,240,255,.9)',lineWidth:1,radius:2.6});if(i===0){const pinchDistance=dist(lm[4],lm[8]),indexTip=lm[8],screenX=indexTip.x*innerWidth,screenY=indexTip.y*innerHeight,mirroredX=innerWidth-screenX,didSwipe=detectSwipe(indexTip.x),gesture=classify(lm,pinchDistance,didSwipe),isPinching=gesture==='PINCH';els.pinch.textContent=pinchDistance.toFixed(3);emitGesture(gesture,{hands:list.length,pinchDistance,cursor:{x:mirroredX,y:screenY},landmarks:lm});updateCursor(mirroredX,screenY,isPinching)}})}
async function loop(now){if(!running)return;if(els.video.currentTime!==lastVideoTime&&handLandmarker){lastVideoTime=els.video.currentTime;const t0=performance.now(),results=handLandmarker.detectForVideo(els.video,now);els.latency.textContent=`${Math.round(performance.now()-t0)} ms`;draw(results)}frameCounter++;if(now-fpsTick>500){els.fps.textContent=Math.round(frameCounter*1000/(now-fpsTick));frameCounter=0;fpsTick=now}requestAnimationFrame(loop)}
els.startBtn.addEventListener('click',startCamera);els.demoBtn.addEventListener('click',()=>{els.overlay.style.display='none';els.tracking.textContent='DEMO';els.hands.textContent='1';emitGesture('OPEN',{hands:1,cursor:{x:innerWidth/2,y:innerHeight/2},demo:true})});
addEventListener('pagehide',()=>stream?.getTracks().forEach(t=>t.stop()));