import{HandLandmarker,FilesetResolver,DrawingUtils}from"https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/+esm";
const q=s=>document.querySelector(s),qa=s=>document.querySelectorAll(s);
const els={video:q('#video'),canvas:q('#stage'),fps:q('#fps'),hands:q('#hands'),points:q('#fingerPoints'),gesture:q('#gestureText'),tracking:q('#trackingState'),pinch:q('#pinchVal'),latency:q('#latency'),cursor:q('#cursor'),overlay:q('#startOverlay'),notice:q('#notice'),toast:q('#toast'),startBtn:q('#startBtn'),demoBtn:q('#demoBtn')};
const ctx=els.canvas.getContext('2d');
let handLandmarker=null,drawingUtils=null,running=false,lastVideoTime=-1,frameCounter=0,fpsTick=performance.now(),stream=null,vision=null,modelsReady=false;
const connections=HandLandmarker.HAND_CONNECTIONS,tipIds=[4,8,12,16,20];
function resize(){const dpr=Math.min(devicePixelRatio||1,2);els.canvas.width=Math.round(innerWidth*dpr);els.canvas.height=Math.round(innerHeight*dpr);els.canvas.style.width=innerWidth+'px';els.canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const fingerExtended=(lm,tip,pip)=>lm[tip].y<lm[pip].y-.025;
function classify(lm,pinchDistance){if(pinchDistance<.055)return'PINCH';const index=fingerExtended(lm,8,6),middle=fingerExtended(lm,12,10),ring=fingerExtended(lm,16,14),pinky=fingerExtended(lm,20,18);const up=[index,middle,ring,pinky].filter(Boolean).length;if(up>=4)return'OPEN';if(up===0)return'FIST';if(index&&!middle&&!ring&&!pinky)return'POINT';return'TRACK'}
function emitGesture(name){els.gesture.textContent=name;qa('.gesture').forEach(el=>el.classList.toggle('active',el.dataset.gesture===name))}
function showToast(text){els.toast.textContent=text;els.toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>els.toast.classList.remove('show'),700)}
function updateCursor(x,y,pinch){els.cursor.style.opacity='1';els.cursor.style.left=`${x}px`;els.cursor.style.top=`${y}px`;els.cursor.classList.toggle('pinching',pinch)}
async function initModel(){if(modelsReady)return;els.notice.textContent='相機已允許，正在載入雙手追蹤模型…';vision=vision||await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');handLandmarker=await HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.5});drawingUtils=new DrawingUtils(ctx);modelsReady=true;els.notice.textContent='雙手追蹤完成，正在啟動…'}
function permissionHelp(err){const name=err?.name||'';if(name==='NotAllowedError'||name==='PermissionDeniedError'||String(err?.message||'').includes('not allowed'))return'相機權限被瀏覽器擋住。Safari：網站設定 → 相機 → 允許，再重新整理。';if(name==='NotFoundError')return'找不到可用相機。';if(!isSecureContext)return'相機只能在 HTTPS 安全頁面使用。';return`啟動失敗：${err?.message||err}`}
async function startCamera(){els.startBtn.disabled=true;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('此瀏覽器不支援相機存取');els.notice.textContent='正在要求相機權限…';stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});await initModel();els.video.srcObject=stream;await els.video.play();running=true;els.overlay.style.display='none';els.tracking.textContent='ONLINE';requestAnimationFrame(loop)}catch(err){console.error(err);stream?.getTracks().forEach(t=>t.stop());stream=null;els.notice.textContent=permissionHelp(err);els.startBtn.disabled=false}}
function normalizeHand(lm,gesture,pinchDistance,label,index){const fingertips=tipIds.map(id=>({x:innerWidth-lm[id].x*innerWidth,y:lm[id].y*innerHeight,z:lm[id].z||0}));return{index,label,gesture,pinchDistance,landmarks:lm,fingertips,wrist:{x:innerWidth-lm[0].x*innerWidth,y:lm[0].y*innerHeight,z:lm[0].z||0},cursor:fingertips[1]}}
function draw(results,now){ctx.clearRect(0,0,innerWidth,innerHeight);if(els.video.readyState>=2){ctx.save();ctx.globalAlpha=.76;ctx.drawImage(els.video,0,0,innerWidth,innerHeight);ctx.restore()}const list=results?.landmarks||[],handed=results?.handednesses||results?.handedness||[];els.hands.textContent=list.length;els.points.textContent=`${Math.min(10,list.length*5)}/10`;if(!list.length){els.cursor.style.opacity='0';els.pinch.textContent='—';emitGesture('—');dispatchEvent(new CustomEvent('qookey-frame',{detail:{hands:[],now}}));return}const out=[];list.forEach((lm,i)=>{const pinchDistance=dist(lm[4],lm[8]),gesture=classify(lm,pinchDistance),label=handed?.[i]?.[0]?.categoryName||handed?.[i]?.[0]?.displayName||`HAND ${i+1}`;drawingUtils.drawConnectors(lm,connections,{color:'rgba(139,240,255,.62)',lineWidth:2});drawingUtils.drawLandmarks(lm,{color:'#f1feff',fillColor:'rgba(139,240,255,.92)',lineWidth:1,radius:2.7});out.push(normalizeHand(lm,gesture,pinchDistance,label,i));if(i===0){els.pinch.textContent=pinchDistance.toFixed(3);emitGesture(gesture);updateCursor(innerWidth-lm[8].x*innerWidth,lm[8].y*innerHeight,gesture==='PINCH')}});dispatchEvent(new CustomEvent('qookey-frame',{detail:{hands:out,now}}))}
async function loop(now){if(!running)return;if(els.video.currentTime!==lastVideoTime&&handLandmarker){lastVideoTime=els.video.currentTime;const t0=performance.now(),results=handLandmarker.detectForVideo(els.video,now);els.latency.textContent=`${Math.round(performance.now()-t0)} ms`;draw(results,now)}frameCounter++;if(now-fpsTick>500){els.fps.textContent=Math.round(frameCounter*1000/(now-fpsTick));frameCounter=0;fpsTick=now}requestAnimationFrame(loop)}
els.startBtn.addEventListener('click',startCamera);
els.demoBtn.addEventListener('click',()=>{els.overlay.style.display='none';els.tracking.textContent='DEMO';dispatchEvent(new CustomEvent('qookey-demo'));showToast('DEMO')});
addEventListener('pagehide',()=>{stream?.getTracks().forEach(t=>t.stop());handLandmarker?.close?.()});
