import{HandLandmarker,FilesetResolver,DrawingUtils}from"https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/+esm";
const q=s=>document.querySelector(s);
const els={video:q('#video'),canvas:q('#stage'),fps:q('#fps'),hands:q('#hands'),mode:q('#gestureText'),tracking:q('#trackingState'),latency:q('#latency'),overlay:q('#startOverlay'),notice:q('#notice'),toast:q('#toast'),startBtn:q('#startBtn'),demoBtn:q('#demoBtn')};
const ctx=els.canvas.getContext('2d');
let handLandmarker=null,drawingUtils=null,running=false,lastVideoTime=-1,frameCounter=0,fpsTick=performance.now(),stream=null,vision=null,modelsReady=false;
const connections=HandLandmarker.HAND_CONNECTIONS;
function resize(){const dpr=Math.min(devicePixelRatio||1,2);els.canvas.width=Math.round(innerWidth*dpr);els.canvas.height=Math.round(innerHeight*dpr);els.canvas.style.width=innerWidth+'px';els.canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
function palmCenter(lm){const ids=[0,5,9,13,17];let x=0,y=0,z=0;for(const id of ids){x+=lm[id].x;y+=lm[id].y;z+=lm[id].z||0}return{x:innerWidth-(x/ids.length)*innerWidth,y:(y/ids.length)*innerHeight,z:z/ids.length}}
function showToast(text){els.toast.textContent=text;els.toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>els.toast.classList.remove('show'),650)}
async function initModel(){if(modelsReady)return;els.notice.textContent='相機已允許，正在載入雙手追蹤模型…';vision=vision||await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');handLandmarker=await HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.5});drawingUtils=new DrawingUtils(ctx);modelsReady=true;els.notice.textContent='雙手追蹤完成，正在啟動…'}
function permissionHelp(err){const name=err?.name||'';if(name==='NotAllowedError'||name==='PermissionDeniedError'||String(err?.message||'').includes('not allowed'))return'相機權限被瀏覽器擋住。Safari：網站設定 → 相機 → 允許，再重新整理。';if(name==='NotFoundError')return'找不到可用相機。';if(!isSecureContext)return'相機只能在 HTTPS 安全頁面使用。';return`啟動失敗：${err?.message||err}`}
async function startCamera(){els.startBtn.disabled=true;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('此瀏覽器不支援相機存取');els.notice.textContent='正在要求相機權限…';stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});await initModel();els.video.srcObject=stream;await els.video.play();running=true;els.overlay.style.display='none';els.tracking.textContent='ONLINE';requestAnimationFrame(loop)}catch(err){console.error(err);stream?.getTracks().forEach(t=>t.stop());stream=null;els.notice.textContent=permissionHelp(err);els.startBtn.disabled=false}}
function draw(results,now){ctx.clearRect(0,0,innerWidth,innerHeight);if(els.video.readyState>=2){ctx.save();ctx.globalAlpha=.8;ctx.drawImage(els.video,0,0,innerWidth,innerHeight);ctx.restore()}const list=results?.landmarks||[];els.hands.textContent=list.length;els.mode.textContent=list.length>=2?'PLAY':list.length===1?'ONE HAND':'WAIT';const out=[];list.forEach((lm,i)=>{drawingUtils.drawConnectors(lm,connections,{color:'rgba(255,205,142,.48)',lineWidth:1.7});drawingUtils.drawLandmarks(lm,{color:'#fff5df',fillColor:'rgba(229,139,75,.92)',lineWidth:1,radius:2.5});out.push({index:i,landmarks:lm,palm:palmCenter(lm)})});dispatchEvent(new CustomEvent('qookey-frame',{detail:{hands:out,now}}))}
async function loop(now){if(!running)return;if(els.video.currentTime!==lastVideoTime&&handLandmarker){lastVideoTime=els.video.currentTime;const t0=performance.now(),results=handLandmarker.detectForVideo(els.video,now);els.latency.textContent=`${Math.round(performance.now()-t0)} ms`;draw(results,now)}frameCounter++;if(now-fpsTick>500){els.fps.textContent=Math.round(frameCounter*1000/(now-fpsTick));frameCounter=0;fpsTick=now}requestAnimationFrame(loop)}
els.startBtn.addEventListener('click',startCamera);
els.demoBtn.addEventListener('click',()=>{els.overlay.style.display='none';els.tracking.textContent='DEMO';els.hands.textContent='2';els.mode.textContent='PLAY';dispatchEvent(new CustomEvent('qookey-demo'));showToast('DEMO')});
addEventListener('pagehide',()=>{stream?.getTracks().forEach(t=>t.stop());handLandmarker?.close?.()});
