import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const canvas=document.querySelector('#cubeStage'),stateEl=document.querySelector('#cubeState'),faceEl=document.querySelector('#selectedFace'),moveEl=document.querySelector('#moveCount'),toast=document.querySelector('#toast'),scrambleBtn=document.querySelector('#scrambleBtn'),resetBtn=document.querySelector('#resetBtn');
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(0,0,9.3);
scene.add(new THREE.HemisphereLight(0xe8fbff,0x101722,2.1));const key=new THREE.DirectionalLight(0xffffff,2.5);key.position.set(4,6,8);scene.add(key);const rim=new THREE.DirectionalLight(0x70dfff,1.4);rim.position.set(-5,-2,5);scene.add(rim);
const cubeRoot=new THREE.Group();scene.add(cubeRoot);cubeRoot.rotation.set(-.38,.62,.08);
const spacing=1.02,size=.91,cubies=[],meshes=[];let moves=0,turning=false,targetScale=1,orbitX=cubeRoot.rotation.x,orbitY=cubeRoot.rotation.y,lastOrbit=null,pinchSession=null,lastPrimaryPinch=false;
const C={R:0xff4a4a,L:0xff8a2b,U:0xf7f7f2,D:0xffe148,F:0x35cf70,B:0x3c78ff,I:0x10151c};
function mat(color){return new THREE.MeshStandardMaterial({color,roughness:.38,metalness:.06})}
const edgeMat=new THREE.LineBasicMaterial({color:0x020507,transparent:true,opacity:.85});
function makeCubie(x,y,z){const materials=[mat(x===1?C.R:C.I),mat(x===-1?C.L:C.I),mat(y===1?C.U:C.I),mat(y===-1?C.D:C.I),mat(z===1?C.F:C.I),mat(z===-1?C.B:C.I)];const mesh=new THREE.Mesh(new THREE.BoxGeometry(size,size,size),materials),g=new THREE.Group();mesh.userData.cubie=g;const edges=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),edgeMat);mesh.add(edges);g.add(mesh);g.position.set(x*spacing,y*spacing,z*spacing);g.userData.coord=new THREE.Vector3(x,y,z);cubeRoot.add(g);cubies.push(g);meshes.push(mesh)}
for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++)makeCubie(x,y,z);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function toastMsg(text){toast.textContent=text;toast.classList.add('show');clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove('show'),650)}
function raycastAt(x,y){pointer.x=x/innerWidth*2-1;pointer.y=-(y/innerHeight)*2+1;raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(meshes,false)[0]||null}
function faceFromHit(hit){if(!hit?.face)return null;const nm=new THREE.Matrix3().getNormalMatrix(hit.object.matrixWorld),world=hit.face.normal.clone().applyMatrix3(nm).normalize(),q=new THREE.Quaternion();cubeRoot.getWorldQuaternion(q);world.applyQuaternion(q.invert());const a={x:Math.abs(world.x),y:Math.abs(world.y),z:Math.abs(world.z)};let axis='x';if(a.y>a.x&&a.y>=a.z)axis='y';else if(a.z>a.x&&a.z>a.y)axis='z';const sign=Math.sign(world[axis])||1;return{axis,layer:sign,label:`${sign>0?'+':'−'}${axis.toUpperCase()}`}}
function rotateCoord(v,axis,angle){const m=new THREE.Matrix4();if(axis==='x')m.makeRotationX(angle);if(axis==='y')m.makeRotationY(angle);if(axis==='z')m.makeRotationZ(angle);v.applyMatrix4(m);v.set(Math.round(v.x),Math.round(v.y),Math.round(v.z))}
function turnLayer(axis,layer,dir,animate=true){if(turning)return false;turning=true;stateEl.textContent='TURNING';const chosen=cubies.filter(c=>Math.round(c.userData.coord[axis])===layer),pivot=new THREE.Group();cubeRoot.add(pivot);chosen.forEach(c=>pivot.add(c));const angle=dir*Math.PI/2,duration=animate?190:1,start=performance.now();function step(now){const t=Math.min(1,(now-start)/duration),e=1-Math.pow(1-t,3);pivot.rotation[axis]=angle*e;if(t<1){requestAnimationFrame(step);return}pivot.rotation[axis]=angle;pivot.updateMatrixWorld(true);chosen.forEach(c=>{cubeRoot.attach(c);rotateCoord(c.userData.coord,axis,angle);c.position.set(c.userData.coord.x*spacing,c.userData.coord.y*spacing,c.userData.coord.z*spacing);c.quaternion.normalize()});cubeRoot.remove(pivot);turning=false;moves++;moveEl.textContent=moves;stateEl.textContent='READY'}requestAnimationFrame(step);return true}
function dragDirection(axis,layer,dx,dy){const dominant=Math.abs(dx)>Math.abs(dy)?dx:-dy;return(dominant>=0?1:-1)*layer*(axis==='z'?-1:1)}
function beginPinch(hand){const hit=raycastAt(hand.cursor.x,hand.cursor.y),face=faceFromHit(hit);pinchSession=face?{face,startX:hand.cursor.x,startY:hand.cursor.y,done:false}:null;faceEl.textContent=face?.label||'—';if(face)stateEl.textContent='GRABBED'}
function updatePinch(hand){if(!pinchSession||pinchSession.done||turning)return;const dx=hand.cursor.x-pinchSession.startX,dy=hand.cursor.y-pinchSession.startY;if(Math.hypot(dx,dy)<52)return;const {axis,layer,label}=pinchSession.face,dir=dragDirection(axis,layer,dx,dy);if(turnLayer(axis,layer,dir,true)){pinchSession.done=true;toastMsg(`${label} 90°`)}}
function endPinch(){pinchSession=null;if(!turning)stateEl.textContent='READY';faceEl.textContent='—'}
function handleOrbit(hands){const open=hands.filter(h=>h.gesture==='OPEN');if(!open.length||turning){lastOrbit=null;return}const controller=open.length>1?open[1]:open[0],p=controller.wrist;if(lastOrbit){const dx=(p.x-lastOrbit.x)/innerWidth,dy=(p.y-lastOrbit.y)/innerHeight;orbitY+=dx*4.1;orbitX+=dy*3.6;orbitX=Math.max(-1.2,Math.min(1.2,orbitX))}lastOrbit={x:p.x,y:p.y};if(open.length>=2){const a=open[0].wrist,b=open[1].wrist,d=Math.hypot(a.x-b.x,a.y-b.y)/Math.min(innerWidth,innerHeight);targetScale=Math.max(.72,Math.min(1.42,.55+d*1.15))}}
addEventListener('qookey-frame',e=>{const hands=e.detail?.hands||[],primary=hands[0];if(primary){const pinching=primary.gesture==='PINCH';if(pinching&&!lastPrimaryPinch)beginPinch(primary);if(pinching)updatePinch(primary);if(!pinching&&lastPrimaryPinch)endPinch();lastPrimaryPinch=pinching}else{if(lastPrimaryPinch)endPinch();lastPrimaryPinch=false}handleOrbit(hands)});
function clearCube(){while(cubeRoot.children.length)cubeRoot.remove(cubeRoot.children[0]);cubies.length=0;meshes.length=0}
function resetCube(){if(turning)return;clearCube();for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++)makeCubie(x,y,z);moves=0;moveEl.textContent='0';orbitX=-.38;orbitY=.62;targetScale=1;cubeRoot.rotation.set(orbitX,orbitY,.08);cubeRoot.scale.setScalar(1);stateEl.textContent='READY';faceEl.textContent='—';toastMsg('RESET')}
async function scramble(){if(turning)return;const axes=['x','y','z'];for(let i=0;i<14;i++){const axis=axes[Math.floor(Math.random()*3)],layer=Math.random()>.5?1:-1,dir=Math.random()>.5?1:-1;await new Promise(resolve=>{const before=moves;if(!turnLayer(axis,layer,dir,true)){resolve();return}const tick=()=>moves>before?resolve():setTimeout(tick,20);tick()})}toastMsg('SCRAMBLED')}
scrambleBtn.addEventListener('click',scramble);resetBtn.addEventListener('click',resetCube);
addEventListener('qookey-demo',()=>toastMsg('CUBE READY'));
const scaleVec=new THREE.Vector3();function render(){cubeRoot.rotation.x+=(orbitX-cubeRoot.rotation.x)*.08;cubeRoot.rotation.y+=(orbitY-cubeRoot.rotation.y)*.08;scaleVec.setScalar(targetScale);cubeRoot.scale.lerp(scaleVec,.08);renderer.render(scene,camera);requestAnimationFrame(render)}render();
