const canvas=document.querySelector('#foxStage'),ctx=canvas.getContext('2d'),app=document.querySelector('#app'),modeBtn=document.querySelector('#modeBtn'),modeText=document.querySelector('#modeText'),pointsText=document.querySelector('#fingerPoints'),foxState=document.querySelector('#foxState');
const TIP_IDS=[4,8,12,16,20],WARM=['#ffd7a8','#ffb56b','#ff8fa8','#fff1dc','#ffa37f'];
let frame={hands:[],gestures:[],face:null,pose:null,now:0},particles=[],charged=false,lastCenter={x:innerWidth/2,y:innerHeight/2},demo=false,demoT=0;
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
modeBtn?.addEventListener('click',()=>{app.classList.toggle('core-mode');const core=app.classList.contains('core-mode');modeText.textContent=core?'CORE':'FOX';modeBtn.setAttribute('aria-pressed',String(core));});
addEventListener('qookey-demo',()=>{demo=true});
addEventListener('qookey-frame',e=>{demo=false;frame=e.detail||frame;const tips=getTips(frame.hands);pointsText.textContent=`${Math.min(10,tips.length)}/10`;foxState.textContent=frame.face&&frame.pose?'FACE + BODY':frame.face?'FACE':frame.pose?'BODY':'HANDS';const bothFist=frame.gestures.length>=2&&frame.gestures.every(g=>g==='FIST'),bothOpen=frame.gestures.length>=2&&frame.gestures.every(g=>g==='OPEN');if(bothFist)charged=true;if(charged&&bothOpen){spawnBurst(centerOf(tips.length?tips:[lastCenter]),92);charged=false}});
const P=p=>({x:p.x*innerWidth,y:p.y*innerHeight});
function getTips(hands=[]){const out=[];hands.slice(0,2).forEach((lm,hand)=>TIP_IDS.forEach((id,finger)=>{const p=lm?.[id];if(p)out.push({...P(p),hand,finger})}));return out}
function centerOf(points){if(!points.length)return{x:innerWidth/2,y:innerHeight/2};return{x:points.reduce((s,p)=>s+p.x,0)/points.length,y:points.reduce((s,p)=>s+p.y,0)/points.length}}
function hull(points){if(points.length<3)return points;const pts=[...points].sort((a,b)=>a.x===b.x?a.y-b.y:a.x-b.x),cross=(o,a,b)=>(a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x),lo=[],up=[];for(const p of pts){while(lo.length>=2&&cross(lo.at(-2),lo.at(-1),p)<=0)lo.pop();lo.push(p)}for(let i=pts.length-1;i>=0;i--){const p=pts[i];while(up.length>=2&&cross(up.at(-2),up.at(-1),p)<=0)up.pop();up.push(p)}lo.pop();up.pop();return lo.concat(up)}
function pathRound(points){if(points.length<3)return;ctx.beginPath();const n=points.length;for(let i=0;i<n;i++){const a=points[(i+n-1)%n],b=points[i],c=points[(i+1)%n],mx=(a.x+b.x)/2,my=(a.y+b.y)/2,nx=(b.x+c.x)/2,ny=(b.y+c.y)/2;if(i===0)ctx.moveTo(mx,my);ctx.quadraticCurveTo(b.x,b.y,nx,ny)}ctx.closePath()}
function drawMembrane(tips,now){if(tips.length<6)return;const poly=hull(tips),c=centerOf(poly);lastCenter=c;const pulse=.94+Math.sin(now*.004)*.06,g=ctx.createRadialGradient(c.x,c.y,10,c.x,c.y,Math.max(90,Math.min(260,Math.hypot(...poly.map(p=>p.x-c.x),...poly.map(p=>p.y-c.y)))));g.addColorStop(0,'rgba(255,238,215,.19)');g.addColorStop(.42,'rgba(255,166,128,.12)');g.addColorStop(1,'rgba(255,112,157,.025)');ctx.save();ctx.globalCompositeOperation='lighter';pathRound(poly.map(p=>({x:c.x+(p.x-c.x)*pulse,y:c.y+(p.y-c.y)*pulse})));ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='rgba(255,198,145,.35)';ctx.lineWidth=1.4;ctx.shadowColor='rgba(255,132,166,.55)';ctx.shadowBlur=18;ctx.stroke();ctx.shadowBlur=0;if(tips.length>=10){const a=tips.filter(p=>p.hand===0),b=tips.filter(p=>p.hand===1);for(let i=0;i<Math.min(a.length,b.length,5);i++){const p=a[i],q=b[i],mx=(p.x+q.x)/2,my=(p.y+q.y)/2-18-Math.sin(now*.003+i)*11;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.quadraticCurveTo(mx,my,q.x,q.y);ctx.strokeStyle=`rgba(255,${145+i*16},${173+i*7},${.18+i*.025})`;ctx.lineWidth=1;ctx.stroke()}}ctx.restore()}
function star(x,y,r,rot=0){ctx.beginPath();for(let i=0;i<8;i++){const a=rot+i*Math.PI/4,rr=i%2?r:r*.42,px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}
function drawTips(tips,now){ctx.save();ctx.globalCompositeOperation='lighter';tips.forEach((p,i)=>{const r=5+2*Math.sin(now*.006+i),g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,24);g.addColorStop(0,'rgba(255,255,240,.95)');g.addColorStop(.18,'rgba(255,203,143,.72)');g.addColorStop(.6,'rgba(255,133,165,.18)');g.addColorStop(1,'rgba(255,120,160,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,24,0,Math.PI*2);ctx.fill();ctx.fillStyle=WARM[i%WARM.length];star(p.x,p.y,r,now*.001+i);ctx.fill();if(Math.random()<.055)particles.push({x:p.x,y:p.y,vx:(Math.random()-.5)*.35,vy:-.35-Math.random()*.8,life:1,size:1.2+Math.random()*2,color:WARM[i%WARM.length]})});ctx.restore()}
function spawnBurst(c,n=70){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=1.2+Math.random()*4.6;particles.push({x:c.x,y:c.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,size:1.5+Math.random()*3.5,color:WARM[i%WARM.length]})}}
function updateParticles(){ctx.save();ctx.globalCompositeOperation='lighter';for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vx*=.988;p.vy=p.vy*.988+.006;p.life-=.014;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=10;ctx.beginPath();ctx.arc(p.x,p.y,p.size*Math.max(.2,p.life),0,Math.PI*2);ctx.fill();if(p.life<=0)particles.splice(i,1)}ctx.shadowBlur=0;ctx.restore();if(particles.length>240)particles.splice(0,particles.length-240)}
function vis(p){return p&&((p.visibility??1)>.3)}
function drawFurLimb(a,b,width){if(!vis(a)||!vis(b))return;const p=P(a),q=P(b),dx=q.x-p.x,dy=q.y-p.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len;ctx.save();ctx.lineCap='round';ctx.strokeStyle='rgba(244,154,87,.42)';ctx.lineWidth=width;ctx.shadowColor='rgba(255,155,103,.22)';ctx.shadowBlur=12;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,224,190,.14)';ctx.lineWidth=Math.max(2,width*.28);ctx.stroke();ctx.lineWidth=1.2;for(let i=1;i<8;i++){const t=i/8,x=p.x+dx*t,y=p.y+dy*t,s=(i%2?1:-1)*(width*.55);ctx.strokeStyle=i%3===0?'rgba(255,239,218,.24)':'rgba(255,170,111,.28)';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+nx*s*.28,y+ny*s*.28);ctx.stroke()}ctx.restore()}
function drawTail(pose,now,shoulderW){const h1=pose?.[23],h2=pose?.[24];if(!vis(h1)||!vis(h2))return;const a=P(h1),b=P(h2),root={x:(a.x+b.x)/2,y:(a.y+b.y)/2},side=Math.sin(now*.0008)>0?1:-1;ctx.save();ctx.lineCap='round';ctx.strokeStyle='rgba(238,134,71,.42)';ctx.lineWidth=Math.max(26,shoulderW*.22);ctx.shadowColor='rgba(255,154,104,.22)';ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(root.x,root.y);ctx.bezierCurveTo(root.x+side*shoulderW*.55,root.y+shoulderW*.18,root.x+side*shoulderW*.82,root.y-shoulderW*.24,root.x+side*shoulderW*.48,root.y-shoulderW*.46);ctx.stroke();ctx.strokeStyle='rgba(255,238,213,.62)';ctx.lineWidth=Math.max(13,shoulderW*.11);ctx.beginPath();ctx.moveTo(root.x+side*shoulderW*.62,root.y-shoulderW*.31);ctx.quadraticCurveTo(root.x+side*shoulderW*.72,root.y-shoulderW*.42,root.x+side*shoulderW*.48,root.y-shoulderW*.46);ctx.stroke();ctx.restore()}
function drawBody(pose,now){if(!pose)return;const ls=pose[11],rs=pose[12],lh=pose[23],rh=pose[24];if(![ls,rs,lh,rh].every(vis))return;const L=P(ls),R=P(rs),HL=P(lh),HR=P(rh),shoulderW=Math.hypot(R.x-L.x,R.y-L.y);drawTail(pose,now,shoulderW);const grad=ctx.createLinearGradient((L.x+R.x)/2,(L.y+R.y)/2,(HL.x+HR.x)/2,(HL.y+HR.y)/2);grad.addColorStop(0,'rgba(255,177,102,.30)');grad.addColorStop(.55,'rgba(240,139,72,.24)');grad.addColorStop(1,'rgba(198,101,54,.16)');ctx.save();ctx.beginPath();ctx.moveTo(L.x,L.y);ctx.quadraticCurveTo((L.x+R.x)/2,L.y-shoulderW*.08,R.x,R.y);ctx.lineTo(HR.x,HR.y);ctx.quadraticCurveTo((HL.x+HR.x)/2,Math.max(HL.y,HR.y)+shoulderW*.06,HL.x,HL.y);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='rgba(255,211,164,.16)';ctx.lineWidth=2;ctx.stroke();const cx=(L.x+R.x+HL.x+HR.x)/4,top=(L.y+R.y)/2,bottom=(HL.y+HR.y)/2;ctx.beginPath();ctx.moveTo(cx-shoulderW*.12,top+shoulderW*.08);ctx.quadraticCurveTo(cx,top+shoulderW*.02,cx+shoulderW*.12,top+shoulderW*.08);ctx.quadraticCurveTo(cx+shoulderW*.18,(top+bottom)/2,cx,bottom-shoulderW*.02);ctx.quadraticCurveTo(cx-shoulderW*.18,(top+bottom)/2,cx-shoulderW*.12,top+shoulderW*.08);ctx.fillStyle='rgba(255,244,224,.34)';ctx.fill();ctx.restore();const limbW=Math.max(16,shoulderW*.12);drawFurLimb(pose[11],pose[13],limbW);drawFurLimb(pose[13],pose[15],limbW*.86);drawFurLimb(pose[12],pose[14],limbW);drawFurLimb(pose[14],pose[16],limbW*.86);drawFurLimb(pose[23],pose[25],limbW*1.05);drawFurLimb(pose[25],pose[27],limbW*.92);drawFurLimb(pose[24],pose[26],limbW*1.05);drawFurLimb(pose[26],pose[28],limbW*.92)}
function drawEar(x,y,w,h,flip=1){ctx.save();ctx.translate(x,y);ctx.scale(flip,1);ctx.beginPath();ctx.moveTo(0,h*.52);ctx.quadraticCurveTo(-w*.5,h*.18,-w*.12,-h*.52);ctx.quadraticCurveTo(w*.48,h*.05,0,h*.52);ctx.closePath();ctx.fillStyle='rgba(247,149,86,.76)';ctx.fill();ctx.strokeStyle='rgba(255,225,194,.48)';ctx.lineWidth=2;ctx.stroke();ctx.beginPath();ctx.moveTo(-w*.02,h*.31);ctx.quadraticCurveTo(-w*.22,h*.08,-w*.09,-h*.31);ctx.quadraticCurveTo(w*.25,h*.07,-w*.02,h*.31);ctx.fillStyle='rgba(255,174,185,.62)';ctx.fill();ctx.restore()}
function drawFace(face,now){if(!face?.length)return;let minX=1,minY=1,maxX=0,maxY=0;for(const p of face){if(!p)continue;minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y)}const x=minX*innerWidth,y=minY*innerHeight,w=(maxX-minX)*innerWidth,h=(maxY-minY)*innerHeight;if(w<30||h<30)return;const cx=x+w/2,earY=y-h*.12;ctx.save();const glow=ctx.createRadialGradient(cx,y+h*.52,0,cx,y+h*.52,w*.65);glow.addColorStop(0,'rgba(255,178,102,.13)');glow.addColorStop(.72,'rgba(255,149,103,.05)');glow.addColorStop(1,'rgba(255,149,103,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.ellipse(cx,y+h*.54,w*.59,h*.58,0,0,Math.PI*2);ctx.fill();ctx.restore();drawEar(x+w*.22,earY,w*.26,h*.48,1);drawEar(x+w*.78,earY,w*.26,h*.48,-1);const nose=face[1]?P(face[1]):{x:cx,y:y+h*.58},mouth=face[13]?P(face[13]):{x:cx,y:y+h*.72};ctx.save();ctx.fillStyle='rgba(255,246,228,.52)';ctx.shadowColor='rgba(255,224,196,.25)';ctx.shadowBlur=10;ctx.beginPath();ctx.ellipse(nose.x-w*.075,mouth.y-h*.01,w*.16,h*.12,-.08,0,Math.PI*2);ctx.ellipse(nose.x+w*.075,mouth.y-h*.01,w*.16,h*.12,.08,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.moveTo(nose.x,nose.y-h*.018);ctx.lineTo(nose.x-w*.045,nose.y+h*.025);ctx.lineTo(nose.x+w*.045,nose.y+h*.025);ctx.closePath();ctx.fillStyle='rgba(88,59,60,.88)';ctx.fill();const cheekY=y+h*.65;for(const dir of[-1,1]){const bx=cx+dir*w*.29;const blush=ctx.createRadialGradient(bx,cheekY,0,bx,cheekY,w*.11);blush.addColorStop(0,'rgba(255,130,157,.36)');blush.addColorStop(1,'rgba(255,130,157,0)');ctx.fillStyle=blush;ctx.beginPath();ctx.arc(bx,cheekY,w*.12,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,237,220,.46)';ctx.lineWidth=1.5;for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(cx+dir*w*.12,cheekY+i*h*.035);ctx.quadraticCurveTo(cx+dir*w*.31,cheekY+i*h*.055,cx+dir*w*.48,cheekY+i*h*.025);ctx.stroke()}}ctx.strokeStyle='rgba(255,247,231,.62)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(cx-w*.14,y+h*.24);ctx.quadraticCurveTo(cx-w*.04,y+h*.13,cx,y+h*.23);ctx.quadraticCurveTo(cx+w*.04,y+h*.13,cx+w*.14,y+h*.24);ctx.stroke();const eyes=[face[33],face[263]].filter(Boolean).map(P);ctx.globalCompositeOperation='lighter';eyes.forEach((p,i)=>{ctx.fillStyle='rgba(255,225,174,.62)';star(p.x+(i?-1:1)*w*.045,p.y-h*.02,3.5,now*.002+i);ctx.fill()});ctx.restore()}
function demoFrame(now){demoT+=.018;const c={x:innerWidth/2,y:innerHeight*.48},gap=Math.min(innerWidth*.28,250),r=60+Math.sin(demoT)*8,tips=[];for(let hand=0;hand<2;hand++){const sx=hand?1:-1;for(let i=0;i<5;i++){const a=-1.25+i*.62;tips.push({x:c.x+sx*gap+Math.cos(a)*r*sx,y:c.y+Math.sin(a)*r,hand,finger:i})}}drawMembrane(tips,now);drawTips(tips,now);pointsText.textContent='10/10';foxState.textContent='DEMO'}
function draw(now){ctx.clearRect(0,0,innerWidth,innerHeight);if(!app.classList.contains('core-mode')){if(demo)demoFrame(now);else{drawBody(frame.pose,now);drawFace(frame.face,now);const tips=getTips(frame.hands);drawMembrane(tips,now);drawTips(tips,now)}updateParticles()}requestAnimationFrame(draw)}
requestAnimationFrame(draw);