const canvas=document.querySelector('#noodleStage'),ctx=canvas.getContext('2d');
const lengthEl=document.querySelector('#noodleLength'),distanceEl=document.querySelector('#distanceVal'),thicknessEl=document.querySelector('#thicknessVal'),actionEl=document.querySelector('#actionState'),resetBtn=document.querySelector('#resetBtn'),toast=document.querySelector('#toast');
let dpr=1,w=innerWidth,h=innerHeight,left=null,right=null,targetLeft=null,targetRight=null,stretch=0,velocity=0,lastDistance=null,lastTime=performance.now(),demo=false,demoT=0,wobble=0;
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function toastMsg(text){toast.textContent=text;toast.classList.add('show');clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove('show'),600)}
function setTargets(a,b,now){const pair=[a,b].sort((p,q)=>p.x-q.x);targetLeft=pair[0];targetRight=pair[1];const d=Math.hypot(targetRight.x-targetLeft.x,targetRight.y-targetLeft.y),norm=clamp((d-Math.min(w,h)*.14)/(Math.min(w,h)*.72),0,1);stretch=norm;const dt=Math.max(16,now-lastTime);if(lastDistance!==null){const dv=(d-lastDistance)/dt;velocity=velocity*.7+dv*.3;if(velocity>.72&&d>Math.min(w,h)*.42){wobble=1;toastMsg('甩麵！')}}lastDistance=d;lastTime=now;lengthEl.textContent=`${Math.round(stretch*100)}%`;distanceEl.textContent=`${Math.round(d)} px`;const thick=clamp(14-stretch*8,5.5,14);thicknessEl.textContent=`${thick.toFixed(1)} px`;actionEl.textContent=stretch<.25?'靠近':stretch>.78?'拉很長！':'拉麵中'}
addEventListener('qookey-frame',e=>{demo=false;const hands=e.detail?.hands||[],now=e.detail?.now||performance.now();if(hands.length>=2){setTargets(hands[0].palm,hands[1].palm,now)}else{targetLeft=targetRight=null;lastDistance=null;velocity*=.8;lengthEl.textContent='0%';distanceEl.textContent='—';thicknessEl.textContent='—';actionEl.textContent=hands.length===1?'再放一隻手':'等待雙手'}});
addEventListener('qookey-demo',()=>{demo=true;demoT=0;actionEl.textContent='Demo 拉麵中';lengthEl.textContent='55%'});
resetBtn.addEventListener('click',()=>{targetLeft=targetRight=left=right=null;lastDistance=null;stretch=0;velocity=0;wobble=0;lengthEl.textContent='0%';distanceEl.textContent='—';thicknessEl.textContent='—';actionEl.textContent='等待雙手';toastMsg('RESET')});
function pointLerp(a,b,t){return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}
function drawHandle(p){ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='rgba(255,231,168,.18)';ctx.strokeStyle='rgba(255,222,145,.88)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fillStyle='#fff0bd';ctx.fill();ctx.restore()}
function drawNoodles(a,b,time){const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),nx=d?(-dy/d):0,ny=d?(dx/d):1,baseThickness=clamp(14-stretch*8,5.5,14),sag=clamp(54-d*.035,10,52),shake=wobble*18+Math.min(18,Math.abs(velocity)*12);for(let strand=0;strand<7;strand++){const offset=(strand-3)*baseThickness*.44;ctx.beginPath();for(let i=0;i<=36;i++){const t=i/36,p=pointLerp(a,b,t),arch=Math.sin(Math.PI*t)*sag,wave=Math.sin(t*18+time*.012+strand*.9)*shake*Math.sin(Math.PI*t),x=p.x+nx*(offset+wave),y=p.y+ny*(offset+wave)+arch;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=strand%2?'rgba(255,227,165,.96)':'rgba(255,242,202,.98)';ctx.lineWidth=baseThickness*(strand%2?.72:.9);ctx.shadowColor='rgba(255,196,99,.28)';ctx.shadowBlur=10;ctx.stroke()}ctx.shadowBlur=0;drawHandle(a);drawHandle(b)}
function drawWaiting(){ctx.save();ctx.textAlign='center';ctx.fillStyle='rgba(255,244,220,.62)';ctx.font='600 15px ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.fillText('把兩隻手放進畫面 🍜',w/2,h*.52);ctx.restore()}
function render(now){ctx.clearRect(0,0,w,h);if(demo){demoT+=.018;const span=w*(.22+.18*(Math.sin(demoT*.8)*.5+.5)),cy=h*.5+Math.sin(demoT*.6)*18;targetLeft={x:w/2-span,y:cy+Math.sin(demoT)*12};targetRight={x:w/2+span,y:cy-Math.sin(demoT)*12};stretch=clamp((span*2)/(w*.72),0,1);wobble=.28+Math.abs(Math.sin(demoT*1.7))*.22}if(targetLeft&&targetRight){left=left||{...targetLeft};right=right||{...targetRight};left.x+=(targetLeft.x-left.x)*.22;left.y+=(targetLeft.y-left.y)*.22;right.x+=(targetRight.x-right.x)*.22;right.y+=(targetRight.y-right.y)*.22;drawNoodles(left,right,now)}else drawWaiting();wobble*=.93;velocity*=.93;requestAnimationFrame(render)}requestAnimationFrame(render);
