const canvas=document.querySelector('#orbStage'),ctx=canvas.getContext('2d'),stateEl=document.querySelector('#orbState'),openEl=document.querySelector('#orbOpenVal'),caption=document.querySelector('#orbCaption');
const count=360,golden=Math.PI*(3-Math.sqrt(5));const particles=Array.from({length:count},(_,i)=>{const y=1-i/(count-1)*2,r=Math.sqrt(Math.max(0,1-y*y)),theta=golden*i;return{x:Math.cos(theta)*r,y,z:Math.sin(theta)*r,phase:(i*.61803398875)%1,shard:i%7}});
let openness=.15,target=.15,rot=0,handX=.5,handY=.5,demo=false;
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function targetFor(g,hands){if(demo)return 1;if(!hands)return .15;if(g==='OPEN')return 1;if(g==='FIST')return .02;if(g==='PINCH')return .08;if(g==='POINT')return .3;if(g==='SWIPE')return .68;return .48}
addEventListener('qookey-gesture',e=>{const d=e.detail||{};demo=!!d.demo;target=targetFor(d.gesture,d.hands);if(d.cursor){handX=d.cursor.x/Math.max(innerWidth,1);handY=d.cursor.y/Math.max(innerHeight,1)}});
function draw(now){openness+=(target-openness)*.075;rot+=.0022+openness*.0026;const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const cx=w*.5+(handX-.5)*34*openness,cy=h*.49+(handY-.5)*22*openness,base=Math.max(54,Math.min(108,Math.min(w,h)*.105)),radius=base*(.78+openness*.68),pulse=1+Math.sin(now*.0022)*.025;
const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,radius*1.5);glow.addColorStop(0,`rgba(220,253,255,${.17+openness*.15})`);glow.addColorStop(.28,`rgba(139,240,255,${.12+openness*.09})`);glow.addColorStop(.68,`rgba(95,120,255,${.045+openness*.045})`);glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,radius*1.5,0,Math.PI*2);ctx.fill();
ctx.save();ctx.translate(cx,cy);ctx.rotate((handX-.5)*.16);for(let ring=0;ring<3;ring++){const s=1+ring*.22+openness*(.28+ring*.08);ctx.beginPath();ctx.ellipse(0,0,radius*s,radius*(.28+ring*.08),rot*(ring%2?-1:1)+ring*.7,0,Math.PI*2);ctx.strokeStyle=`rgba(139,240,255,${.08+openness*.11-ring*.018})`;ctx.lineWidth=1;ctx.stroke()}ctx.restore();
const cosY=Math.cos(rot),sinY=Math.sin(rot),tilt=(handY-.5)*.5+Math.sin(now*.0007)*.08,cosX=Math.cos(tilt),sinX=Math.sin(tilt),points=[];for(const p of particles){const rx=p.x*cosY-p.z*sinY;let rz=p.x*sinY+p.z*cosY;const ry=p.y*cosX-rz*sinX;rz=p.y*sinX+rz*cosX;const a=p.shard/7*Math.PI*2,petal=1+openness*(.34+.12*Math.sin(a+now*.0014)),splitX=Math.cos(a)*openness*base*.16*Math.abs(ry),splitY=Math.sin(a)*openness*base*.11*Math.abs(rx),px=rx*radius*petal*pulse+splitX,py=ry*radius*(1+openness*.28)*pulse+splitY+Math.sign(ry)*openness*base*.12*Math.pow(Math.abs(ry),.55),perspective=1+rz*.18;points.push({x:cx+px*perspective,y:cy+py*perspective,z:rz,phase:p.phase})}points.sort((a,b)=>a.z-b.z);for(const p of points){const depth=(p.z+1)*.5,sparkle=.72+Math.sin(now*.003+p.phase*18)*.28,size=.7+depth*1.55+openness*.42;ctx.beginPath();ctx.arc(p.x,p.y,size,0,Math.PI*2);ctx.fillStyle=`rgba(${Math.round(165+depth*78)},${Math.round(224+depth*28)},255,${(.22+depth*.58)*sparkle})`;ctx.fill()}
ctx.beginPath();ctx.arc(cx,cy,5+openness*5,0,Math.PI*2);ctx.fillStyle=`rgba(235,253,255,${.72+openness*.2})`;ctx.shadowColor='rgba(139,240,255,.95)';ctx.shadowBlur=24+openness*30;ctx.fill();ctx.shadowBlur=0;const pct=Math.round(openness*100);openEl.textContent=pct+'%';stateEl.textContent=pct>82?'EXPANDED':pct<16?'CLOSED':`OPEN ${pct}%`;caption.style.opacity=String(.4+openness*.6);requestAnimationFrame(draw)}requestAnimationFrame(draw);